# Generated by Django 3.0.1 on 2020-01-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moonboard', '0002_auto_20200102_1505'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problemmove',
            unique_together={('problem', 'position')},
        ),
    ]
