# Generated by Django 3.0.1 on 2020-01-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonboard', '0004_problem_setyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemmove',
            name='isend',
            field=models.IntegerField(null=True),
        ),
    ]
