# Generated by Django 3.0.1 on 2020-01-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonboard', '0005_auto_20200116_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='setyear',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problemmove',
            name='isend',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
