# Generated by Django 3.0.1 on 2020-03-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonboard', '0006_auto_20200116_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='dateinserted',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='rating',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='repeats',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='setangle',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='problemmove',
            name='setangle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
